resources:
  - url: /local/lovelace/mini-media-player-bundle.js
    type: module
  - url: /local/lovelace/tracker-card/tracker-card.js?track=true
    type: module

# Images for Afvalwijzer
x-afval-images: &afval-images
                state_image:
                  "gft": /local/mijnafvalwijzer/gft3.png
                  "papier": /local/mijnafvalwijzer/papier3.png
                  "restafval": /local/mijnafvalwijzer/rest3.png
                  "pmd": /local/mijnafvalwijzer/plastic3.png
                  "kerstbomen": /local/mijnafvalwijzer/kerstbomen_134.png
                  "Geen": /local/mijnafvalwijzer/kliko3.png

title: EelCapone's home
views:
  - title: Home
    id: view-home
    icon: mdi:home
    panel: false
    cards:
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.power_consumption
            name: Huidig stroomverbruik
            graph: line
            detail: 2
          - type: entities
            id: card-power
            title: Power
            show_header_toggle: false
            entities:
              - sensor.power_consumption
              - sensor.power_tariff
              - sensor.power_consumption_normal
              - sensor.power_consumption_low
              - sensor.voltage_phase_l1
              - sensor.nut_ups_input_voltage
              - sensor.nut_ups_status
              - sensor.nut_ups_battery_charge
              - sensor.ups_battery_runtime_friendly
          - type: history-graph
            id: history-energy
            title: 'Stroomverbruik'
            entities:
              - sensor.power_consumption
              - sensor.power_consumption_normal
              - sensor.power_consumption_low
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.gas_consumption
            name: Huidig gasverbruik
            graph: line
            detail: 2
          - type: history-graph
            id: history-gas
            title: 'Gasverbruik'
            entities:
              - sensor.gas_consumption
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          title: Afval vandaag en morgen
          cards:
            - type: conditional
              conditions:
                - entity: sensor.trash_today_desc
                  state_not: "Geen"
              card:
                type: picture-entity
                entity: sensor.trash_today_desc
                name: sensor.trash_today_desc
                <<: *afval-images
            - type: conditional
              conditions:
                - entity: sensor.trash_tomorrow_desc
                  state_not: "Geen"
              card:
                type: picture-entity
                entity: sensor.trash_tomorrow_desc
                name: sensor.trash_tomorrow_desc
                <<: *afval-images
        - type: glance
          title: Afvalkalender
          entities:
            - sensor.trash_gft_date
            - sensor.trash_papier_date
            - sensor.trash_pmd_date
            - sensor.trash_restafval_date
            - sensor.trash_kerstbomen_date
        - type: entities
          title: Scheduled Deliveries
          show_header_toggle: false
          entities:
            - sensor.dpd
            - sensor.dhl
            - sensor.fedex
            - sensor.gls
            - sensor.postnl
            - sensor.ups
            - sensor.usps
            - sensor.all_deliveries

  - title: Climate
    id: view-climate
    icon: mdi:leaf
    cards:
      - type: vertical-stack
        title: Weather
        cards:
          - type: weather-forecast
            name: Weather Forecast
            entity: weather.buienradar
          - type: glance
            title: Environment
            entities:
              - sensor.current_uv_index
              - sensor.max_uv_index
              - sensor.current_ozone_level
              - sensor.waqi_nijensteinheerd_groningen
          - type: glance
            title: Sun & Moon
            entities:
              - sensor.sunrise
              - sensor.sunset
              - sensor.day_night
              - sensor.moon
              - sensor.season
      - type: vertical-stack
        title: Weather radar
        cards:
          - type: picture-entity
            entity: camera.knmi_weatherradar
            show_name: false
            show_state: false
          - type: picture-entity
            entity: camera.buienradar_forecast
            show_name: false
            show_state: false
      - type: vertical-stack
        title: Climate Control
        cards:
          - type: thermostat
            entity: climate.livingroom
          - type: history-graph
            id: history-temperature
            title: 'Temperature'
            entities:
              - sensor.livingroom_temperature
              - sensor.outdoor_temperature

  - title: Living Room
    id: view-livingroom
    icon: mdi:sofa
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Living Room
            entities:
              - light.dinnertable
              - switch.lamp_dining_window
              - switch.lamp_couch
              - switch.lamp_couch_window
          - type: entities
            title: Media Players
            show_header_toggle: false
            entities:
              - type: custom:mini-media-player
                entity: media_player.livingroom_amp
                artwork_border: true
                group: true
                hide_controls: false
                hide_power: false
                power_color: true
                show_source: true
                show_tts: google
              - type: custom:mini-media-player
                entity: media_player.livingroom_tv
                artwork_border: true
                group: true
                hide_controls: false
                hide_power: false
                power_color: true
                show_source: true
                show_tts: google
          - type: glance
            title: Subwoofer
            show_header_toggle: false
            entities:
              - switch.subwoofer
      - type: vertical-stack
        cards:
          - type: entities
            title: Vacuum Cleaner
            show_header_toggle: false
            entities:
              - input_boolean.housecleaning_activated
              - input_number.housecleaning_hour
              - input_number.housecleaning_minutes
              - vacuum.roomba_living_quarters        

  - title: Master Bedroom
    id: view-masterbedroom
    icon: mdi:bed-empty
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Master Bedroom
            entities:
              - light.masterbedroom
          - type: entities
            title: Wake-up alarm clock
            show_header_toggle: false
            entities:
              - sensor.alarm_time
              - input_boolean.bedroom_alarm_clock_enabled
              - input_number.alarmhour
              - input_number.alarmminutes
              - input_number.alarmdelay
      - type: vertical-stack
        cards:
          - type: entities
            title: Media Players
            show_header_toggle: false
            entities:
              - type: custom:mini-media-player
                entity: media_player.master_bedroom_amp
                group: true
                hide_controls: false
                hide_power: false
                power_color: true
                show_source: true
                show_tts: google
              - type: custom:mini-media-player
                entity: media_player.master_bedroom_tv
                group: true
                hide_controls: false
                hide_power: false
                power_color: true
                show_source: true
                show_tts: google

  - title: Hallway
    id: view-hallway
    icon: mdi:stairs
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: Hallway
            entities:
              - light.stairs_l
              - light.stairs_m
              - light.stairs_h
          - type: glance
            title: Hallway
            entities:
              - binary_sensor.stairs_motion
              - sensor.stairs_temperature
              - sensor.stairs_light_level

  - title: Outdoors
    id: view-outdoors
    icon: mdi:terrain
    cards:
      - type: vertical-stack
        title: Outdoor lights
        cards:
          - type: glance
            title: Outdoor lamps
            entities:
              - light.frontdoor

  - title: Persons
    id: view-persons
    icon: mdi:account-multiple
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            title: People
            entities:
              - person.eelco
              - device_tracker.eelcapone_work
              - device_tracker.eelcapone_tablet
      - type: map
        default_zoom: 14
        entities:
          - device_tracker.eelcapone
          - device_tracker.eelcapone_work
          - device_tracker.eelcapone_tablet
          - zone.home

  - title: Cars
    id: view-cars
    icon: mdi:car-multiple
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Seat Leon
            show_header_toggle: false
            entities:
              - sensor.seat_leon_expdate
              - sensor.seat_leon_insured
              - sensor.seat_leon_recall
          - type: entities
            title: Toyota Auris
            show_header_toggle: false
            entities:
              - sensor.toyota_auris_expdate
              - sensor.toyota_auris_insured
              - sensor.toyota_auris_recall
          - type: entities
            title: Bugatti Veyron
            show_header_toggle: false
            entities:
              - sensor.bugatti_veyron_expdate
              - sensor.bugatti_veyron_insured
              - sensor.bugatti_veyron_recall
          - type: entities
            title: Chevrolet Nubira
            show_header_toggle: false
            entities:
              - sensor.chevrolet_nubira_expdate
              - sensor.chevrolet_nubira_insured
              - sensor.chevrolet_nubira_recall

  - title: Configuration
    id: view-configuration
    icon: mdi:settings
    cards:
      - type: vertical-stack
        title: System
        cards:
          - type: glance
            title: Synology Disks
            entities:
              - sensor.status_sda
              - sensor.status_sdb
              - sensor.status_smart_sda
              - sensor.status_smart_sdb
              - sensor.status_volume_1
              - sensor.volume_used_volume_1
              - sensor.database_size
          - type: glance
            title: Network status
            entities:
              - sensor.fritz_netmonitor
              - sensor.fritzbox_is_linked
              - sensor.fritzbox_is_connected
              - sensor.fritzbox_uptime
              - sensor.uptime
      - type: vertical-stack
        title: Custom components
        cards:
          - type: custom:tracker-card
            title:
            trackers:
              - sensor.custom_card_tracker
              - sensor.custom_component_tracker
              - sensor.custom_python_script_tracker

