sensor:
  - platform: rdw
    name: !secret car_name
    plate: !secret licenseplate
    dateformat: '%d %b %Y'
    sensors:
      - expdate
      - insured
      - recall
  - platform: rdw
    name: "Toyota Auris"
    plate: 16RSL9
    dateformat: '%d %b %Y'
    sensors:
      - expdate
      - insured
      - recall
  - platform: rdw
    name: "Bugatti Veyron"
    plate: GD314N
    sensors:
      - expdate
      - insured
      - recall
  - platform: rdw
    name: "Chevrolet Nubira"
    plate: 50RJJG
    sensors:
      - expdate
      - insured
      - recall

group:
  car_seat_leon:
    name: !secret car_name
    entities:
      - sensor.seat_leon_expdate
      - sensor.seat_leon_insured
      - sensor.seat_leon_recall

homeassistant:
  customize:
    sensor.seat_leon_expdate:
      friendly_name: "APK Vervaldatum"
    sensor.seat_leon_insured:
      friendly_name: "Verzekeringsstatus"
    sensor.seat_leon_recall:
      friendly_name: "Openstaande terugroepacties"

automation:
    # ------------------------------------------------------- #
    # Notify when the APK date is about to expire             #
    # ------------------------------------------------------- #
  - alias: APK date expiration notification
    initial_state: true
    trigger:
      - platform: template
        value_template: "{{ ((as_timestamp(strptime(states('sensor.seat_leon_expdate'), '%d %b %Y')) / 86400) | int) == ((as_timestamp(strptime(states('sensor.date'), '%Y-%m-%d')) / 86400) | int) + 7 }}"
    action:
      - service: notify.eelco
        data_template:
          title: '*Auto*'
          message: De APK keuring verloopt op {{ states('sensor.seat_leon_expdate') }}. Plan een APK keuring bij de garage.

    # ------------------------------------------------------- #
    # Notify when the car's insurance has expired             #
    # ------------------------------------------------------- #
  - alias: Insurance expiration notification
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.seat_leon_insured
        to: 'False'
    action:
      - service: notify.eelco
        data_template:
          title: '*Auto*'
          message: De auto is niet verzekerd! Sluit een autoverzekering af voordat je ermee de weg op gaat.

    # ------------------------------------------------------- #
    # Notify when a maintenance recall has been issued        #
    # ------------------------------------------------------- #
  - alias: Recall notification
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.seat_leon_recall
        to: 'True'
    action:
      - service: notify.eelco
        data_template:
          title: '*Auto*'
          message: Er is een terugroepactie uitgevaardigd voor de auto. Maak een afspraak bij de garage om het probleem te verhelpen.

