sensor:
  - platform: template
    sensors:
      livingroom_temperature:
        friendly_name: "Livingroom"
        icon_template: mdi:temperature
        unit_of_measurement: "°C"
        value_template: 20.5

climate:
  - platform: generic_thermostat
    name: Livingroom
    heater: switch.gas_boiler
    target_sensor: sensor.livingroom_temperature
    min_temp: 10
    max_temp: 25
    ac_mode: false
    hot_tolerance: 0.5
    cold_tolerance: 0.1
    min_cycle_duration:
      minutes: 5
    keep_alive:
      minutes: 30
    initial_operation_mode: 'auto'
#  - platform: opentherm_gw
#    device: !secret dev_opentherm_gw
#    precision: 0.5

group:
  climate:
    name: "Climate Control"
    entities:
      - climate.ecobee
      - climate.heatpump
      - climate.hvac
      - sensor.livingroom_temperature

