#usps:
#    username: !secret usps_username
#    password: !secret usps_password

#deliveries:
#  - platform: demo

sensor:
#  - platform: fedex
#    username: !secret fedex_username
#    password: !secret fedex_password
#  - platform: postnl
#    username: !secret postnl_username
#    password: !secret postnl_password
  - platform: ups
    username: !secret ups_username
    password: !secret ups_password
  - platform: template
    sensors:
      all_deliveries:
        icon_template: mdi:package-variant-closed
        unit_of_measurement: packages
        value_template: >
          {%-for attribute in states.sensor.postnl.attributes
            if  ((attribute != 'attribution') and (attribute != 'unit_of_measurement') and (attribute != 'friendly_name') and (attribute != 'icon') and (attribute != 'entity_picture')) %}
              {{attribute}} : {{states.sensor.postnl.attributes[attribute] }}
          {%-endfor%}
# Temporary placeholder; will be replaced when this sensor is implemented
  - platform: template
    sensors:
      dpd:
        icon_template: mdi:package-variant-closed
        unit_of_measurement: packages
        value_template: 0
# Temporary placeholder; will be replaced when this sensor is implemented
  - platform: template
    sensors:
      dhl:
        icon_template: mdi:package-variant-closed
        unit_of_measurement: packages
        value_template: 0
  - platform: template
    sensors:
      fedex:
        icon_template: mdi:package-variant-closed
        unit_of_measurement: packages
        value_template: 0
# Temporary placeholder; will be replaced when this sensor is implemented
  - platform: template
    sensors:
      gls:
        icon_template: mdi:package-variant-closed
        unit_of_measurement: packages
        value_template: 0
  - platform: template
    sensors:
      postnl:
        icon_template: mdi:package-variant-closed
        unit_of_measurement: packages
        value_template: 0
  - platform: template
    sensors:
      usps:
        icon_template: mdi:package-variant-closed
        unit_of_measurement: packages
        value_template: 0

homeassistant:
  customize:
    sensor.dpd:
      friendly_name: "DPD"
      entity_picture: /local/deliveries/dpd1.svg
    sensor.dhl:
      friendly_name: "DHL"
      entity_picture: /local/deliveries/dhl3.svg
    sensor.fedex:
      friendly_name: "Fedex"
      entity_picture: /local/deliveries/fedex2.svg
    sensor.gls:
      friendly_name: "GLS"
      entity_picture: /local/deliveries/gls1.svg
    sensor.postnl:
      friendly_name: "PostNL"
      entity_picture: /local/deliveries/postnl2.svg
    sensor.ups:
      friendly_name: "UPS"
      entity_picture: /local/deliveries/ups1.svg
    sensor.usps:
      friendly_name: "USPS"
      entity_picture: /local/deliveries/usps2.svg

group:
  deliveries:
    name: Deliveries
    entities:
      - sensor.all_deliveries
      - sensor.dpd
      - sensor.dhl
      - sensor.fedex
      - sensor.gls
      - sensor.postnl
      - sensor.ups
      - sensor.usps

