sensor:
  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - time_date
      - time_utc
      - beat

group:
  date_time:
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.time_date
      - sensor.time_utc
      - sensor.internet_time

