weather:
  - platform: buienradar
    name: buienradar
    latitude: !secret location_latitude
    longitude: !secret location_longitude
    forecast: true

#  - platform: yweather
#    woeid: !secret stn_woeid
#    monitored_conditions:
#      - weather
#      - weather_current
#      - temp_min
#      - temp_max
#      - wind_speed
#      - pressure
#      - visibility
#      - humidity
#      - temperature

sensor:
#  - platform: yr
#    monitored_conditions:
#      - pressure
#      - symbol
#      - temperature
#      - windSpeed
#  - platform: buienradar
#    name: 'buienradar'
#    latitude: !secret location_latitude
#    longitude: !secret location_longitude
#    forecast: true
#  - platform: openweathermap
#    api_key: !secret key_openweathermap
#    monitored_conditions:
#      - weather
#      - temperature
#      - wind_speed
#      - wind_bearing
#      - humidity
#      - pressure
#      - clouds
#      - rain
#      - snow
#      - weather_code

camera:
  - platform: generic
    name: buienradar_forecast
    still_image_url: https://api.buienradar.nl/image/1.0/RadarMapNL?w=500&h=500
    content_type: 'image/gif'
  - platform: generic
    name: knmi_weatherradar
    still_image_url: https://cdn.knmi.nl/knmi/map/page/weer/actueel-weer/neerslagradar/WWWRADAR_loop.gif
    content_type: 'image/gif'

homeassistant:
#    sensor.yr_symbol:
#      friendly_name: "Weather Symbol"
#    sensor.yr_temperature:
#      friendly_name: "Temperature"
#    sensor.yr_pressure:
#      friendly_name: "Pressure"
#    sensor.yr_wind_speed:
#      friendly_name: "Wind Speed"

group:
  weather:
    name: "Weather"
    entities:
      - sensor.buienradar_symbol
      - sensor.buienradar_symbol_2
      - sensor.buienradar_temperature
      - sensor.buienradar_temperature_2
      - sensor.yr_symbol
      - sensor.yr_temperature
      - sensor.yr_pressure
      - sensor.yr_wind_speed
      - sensor.owm_condition
      - sensor.owm_temperature
      - sensor.owm_wind_speed
      - sensor.owm_wind_bearing
      - sensor.owm_humidity
      - sensor.owm_pressure
      - sensor.owm_cloud_coverage
      - sensor.owm_rain
      - sensor.owm_snow
      - sensor.owm_weather_code

